"""
mantel.py
---------
Permutation-based Mantel test linking pairwise semantic distances to any
participant-level predictor variable.

The test is completely generic: it takes an embeddings dict and a participant-
level Series (age, latitude, income, education level, or any numeric variable)
and returns per-concept Mantel r statistics with permutation p-values.

The only SWOW-specific assumption is the 'participantID' key in the embeddings
dict, which is used to look up predictor values. Any embeddings dict produced
by encode_concepts() will have this key.
"""

import numpy as np
import pandas as pd
from scipy.stats import pearsonr
from itertools import combinations
from tqdm import tqdm


def build_dyads(
    embeddings: dict,
    predictor: pd.Series,
    concepts: list = None,
    predictor_transform=None,
) -> pd.DataFrame:
    """Construct a participant-dyad DataFrame for Mantel analysis.

    For each concept, all unique participant pairs are enumerated. Each dyad
    receives a semantic distance (delta = (1 - cos) / 2) and a predictor
    distance. For ordinary numeric predictors (age, population, GDP, etc.)
    this is the absolute difference between the two participants' values.
    For geographic_distance (a GeoCoordinates object from load_swow_predictors),
    this is instead the great-circle distance between the two participants'
    coordinates. Dyads where either participant lacks a value are dropped.

    Parameters
    ----------
    embeddings : dict
        Concept-keyed dict from encode_concepts().
    predictor : pd.Series or GeoCoordinates
        Participant-level variable indexed by participantID.
        Examples: df_participants.set_index('participantID')['age'],
        or swow_predictors['geographic_distance'].
    concepts : list of str or None
        Concepts to include. If None, all keys in embeddings are used.
    predictor_transform : callable or None
        Optional transform applied to the raw predictor distance, e.g.
        np.log1p for log-scaling. Not applied to geographic_distance.

    Returns
    -------
    pd.DataFrame
        Columns: cue, pid_i, pid_j, delta, predictor_dist.
    """
    from .geo import GeoCoordinates
    is_geo = isinstance(predictor, GeoCoordinates)

    if concepts is None:
        concepts = list(embeddings.keys())

    rows = []

    for concept in tqdm(concepts, desc="Building dyads"):
        if concept not in embeddings:
            continue

        emb_dict = embeddings[concept]
        matrix   = emb_dict["matrix"]
        pids     = emb_dict["participantID"]
        n        = len(pids)

        for idx_i, idx_j in combinations(range(n), 2):
            pid_i = pids[idx_i]
            pid_j = pids[idx_j]

            if pid_i not in predictor.index or pid_j not in predictor.index:
                continue

            val_i = predictor[pid_i]
            val_j = predictor[pid_j]

            if is_geo:
                pred_dist = GeoCoordinates.distance(val_i, val_j)
                if pd.isna(pred_dist):
                    continue
            else:
                if pd.isna(val_i) or pd.isna(val_j):
                    continue
                pred_dist_raw = abs(val_i - val_j)
                pred_dist = predictor_transform(pred_dist_raw) if predictor_transform else pred_dist_raw

            cos_sim = float(matrix[idx_i] @ matrix[idx_j])
            delta   = (1 - cos_sim) / 2

            rows.append((concept, pid_i, pid_j, delta, pred_dist))

    return pd.DataFrame(rows, columns=["cue", "pid_i", "pid_j", "delta", "predictor_dist"])


def mantel_test(
    df_dyads: pd.DataFrame,
    concepts: list = None,
    min_dyads: int = 75,
    n_perm: int = 9999,
    seed: int = 42,
    tail: str = "upper",
) -> pd.DataFrame:
    """Run a permutation-based Mantel test per concept.

    The test statistic is Pearson r between the vectorized upper triangles
    of the semantic and predictor distance matrices. The null distribution
    is generated by randomly permuting participant labels on the predictor
    matrix while keeping the semantic matrix fixed.

    Parameters
    ----------
    df_dyads : pd.DataFrame
        Output of build_dyads(). Must contain columns:
        cue, pid_i, pid_j, delta, predictor_dist.
    concepts : list of str or None
        Concepts to test. If None, all unique values of df_dyads['cue']
        are used.
    min_dyads : int
        Minimum number of dyads required for a concept to be included.
    n_perm : int
        Number of permutations. 9999 gives minimum attainable p = 0.0001.
    seed : int
        Random seed for reproducibility.
    tail : str
        'upper'  : p = P(null >= obs_r)  [predictor predicts divergence]
        'lower'  : p = P(null <= obs_r)  [predictor predicts convergence]
        'both'   : two-tailed

    Returns
    -------
    pd.DataFrame
        Columns: cue, r, p_mantel, N_dyads.
        Sorted by r descending.
    """
    if concepts is None:
        concepts = df_dyads["cue"].unique().tolist()

    rng     = np.random.default_rng(seed)
    results = []

    for concept in concepts:
        grp = df_dyads[
            (df_dyads["cue"] == concept) &
            df_dyads["predictor_dist"].notna()
        ].copy()

        if len(grp) < min_dyads:
            continue

        pids    = pd.unique(pd.concat([grp["pid_i"], grp["pid_j"]]))
        N       = len(pids)
        pid_idx = {p: i for i, p in enumerate(pids)}

        delta_mat = np.zeros((N, N))
        pred_mat  = np.zeros((N, N))

        for _, row in grp.iterrows():
            i = pid_idx[row["pid_i"]]
            j = pid_idx[row["pid_j"]]
            delta_mat[i, j] = delta_mat[j, i] = row["delta"]
            pred_mat[i, j]  = pred_mat[j, i]  = row["predictor_dist"]

        idx      = np.triu_indices(N, k=1)
        d_vec    = delta_mat[idx]
        p_vec    = pred_mat[idx]
        obs_r, _ = pearsonr(d_vec, p_vec)

        null = np.empty(n_perm)
        for b in range(n_perm):
            perm       = rng.permutation(N)
            p_perm     = pred_mat[np.ix_(perm, perm)]
            null[b], _ = pearsonr(d_vec, p_perm[idx])

        if tail == "upper":
            p_val = np.mean(null >= obs_r)
        elif tail == "lower":
            p_val = np.mean(null <= obs_r)
        else:
            p_val = 2 * min(np.mean(null >= obs_r), np.mean(null <= obs_r))

        results.append({"cue": concept, "r": obs_r, "p_mantel": p_val, "N_dyads": len(grp)})

    return (
        pd.DataFrame(results)
        .sort_values("r", ascending=False)
        .reset_index(drop=True)
    )
